name: Build and Test

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
 
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  build-and-test:  
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dotnet: [ '3.1.x', '5.0.x', '6.0.x']
    steps:
    - name: 🛎 Checkout repo
      uses: actions/checkout@v3

    - name: 🚧 Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: ⚙️ Install dependencies
      run: dotnet restore src/GShark/GShark.csproj

    - name: 🏗 Build
      run: dotnet build src/GShark/GShark.csproj --configuration Release --no-restore

    - name: 🧪 Test
      run: dotnet test src/GShark.Test.XUnit/GShark.Test.XUnit.csproj --configuration Release --no-restore
