name: Release drafter

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: 👶 Draft release
        uses: release-drafter/release-drafter@v5
